### ISSUE TITLE
Issue with LTO in 1.16.0

### ISSUE THREAD

**Issue by evanw** [kripken/emscripten#2366]
I recently tried to upgrade our build system to use `emscripten-1.16.0` with `clang-e1.16.0-64bit` but we're getting this build error when building in release:

```
Value: { i32, i32 } %__f.0.0.val
LLVM ERROR: Unrecognized struct value
Traceback (most recent call last):
  File "~/.emsdk_portable/emscripten/1.16.0/emcc", line 1540, in <module>
    shared.Building.llvm_opt(final, link_opts)
  File "~/.emsdk_portable/emscripten/1.16.0/tools/shared.py", line 1267, in llvm_opt
    assert os.path.exists(target), 'Failed to run llvm optimizations: ' + output
AssertionError: Failed to run llvm optimizations: 
```

It was very hard to narrow down but I finally figured out what it was. Reduced test case:

```
#include <functional>

struct Foo {
  void foo() {}
};

std::function<void ()> foo;
Foo bar;

int main() {
  foo = std::bind(&Foo::foo, &bar);
  return 0;
}
```

Makefile used to compile the above code:

```
SDK = ~/.emsdk_portable
EMCC = LLVM=$(SDK)/clang/e1.16.0_64bit python $(SDK)/emscripten/1.16.0/emcc

build:
    $(EMCC) -Os -std=c++11 -c foo.cpp -o foo.bc
    $(EMCC) -Os --llvm-lto 1 foo.bc -o foo.js
```

Is the invocation of the compiler incorrect? Or is this a compiler bug? I would like to take advantage of fastcomp but this seems to be stopping us.

**Comment by wffurr** [comment]
Upstream bug is fixed, looking forward to a release with the changes and being able to use method pointers and std::bind again.

**Comment by kripken** [comment]
Looks assigned, not fixed. Also, I might be reading it wrong, but I don't understand how those commits just linked relate to the issue.

**Comment by wffurr** [comment]
The subzero makefile changes overrides -O3 to always be -O2 because of the bug.

**Comment by kripken** [comment]
Sounds more like a temporary workaround than a fix, then?

**Comment by wffurr** [comment]
Oh, yes.  Premature excitement on my part.

**Comment by juj** [comment]
Trying out the STR with Emscripten 1.37.16 today, it looks like this has been fixed somewhere along the way, so closing as resolved.
