### ISSUE TITLE
getsockname give "unsupported socketcall syscall 6"

### ISSUE THREAD

**Issue by raptor** [kripken/emscripten#3769]
Hi,

Pursuant to finding the problem with the `abort("unsupported socketcall syscall 6")` at runtime after compiling my game with emscripten, I have reduced it down to a test case `.cpp` file:
```
#include <sys/socket.h>

int main() {
   sockaddr address;
   socklen_t addressSize = sizeof(address);

   unsigned int netNum[4];
   signed int socket;

   getsockname(socket, (sockaddr *) &address, &addressSize);

   return 0;
}

```
There are no issues compiling/linking the above code; however at runtime it generates the `abort` that I'm experiencing with my game.

**Comment by kripken** [comment]
Thanks, fixed on incoming.

**Comment by raptor** [comment]
I've just tested your fix.  I am now getting this error when calling `getsockname`:
```TypeError: str is undefined
Stack trace:
__inet_pton4_raw@file:///home/buckd/code/git/bitfighter/exe/bitfighter.js:3339:11
DNS.lookup_name@file:///home/buckd/code/git/bitfighter/exe/bitfighter.js:3406:19
___syscall102@file:///home/buckd/code/git/bitfighter/exe/bitfighter.js:15052:57
_getsockname@file:///home/buckd/code/git/bitfighter/exe/bitfighter.js:516413:22
...
```

**Comment by kripken** [comment]
Does the testcase you provided, and the test I added to the test suite, pass for you? (`./tests/runner.py sockets.test_sockets_echo`) They pass here, so you might be hitting functionality not yet covered by those?

**Comment by raptor** [comment]
Yes, both of those pass (after installing the nodejs 'ws' module).  I've checked other usage of `getsockname` in my code and it's always used in the exact same manner as that test case.

**Comment by kripken** [comment]
The only thing I can think of that could lead to that error is if the socket doesn't have an address yet. I fixed that on incoming, but not sure if it helps your problem or not.

**Comment by raptor** [comment]
I think I see the problem.  `htonl(INADDR_ANY)` is being used to generate address data.  But that symbol is missing because linking my game is still throwing `unresolved symbol: htonl`.  

I need to figure out why it's doing this.  At first I suspected problems with linking `.a` archives so I changed it to a `.so` one, but this didn't fix it.   My test cases isolating my `htonl` usage does not give the error when linking so I'm not sure what to do yet.

**Comment by kripken** [comment]
Try incoming, I also pushed a commit that makes sure `htonl` is linked in when `socket()` is called, when it wasn't earlier.

**Comment by raptor** [comment]
I tried that, with clearing the precompiled cache, but it didn't work, sadly.  

For reference, this is the only compilation unit in my project that uses `htonl`:
https://github.com/bitfighter/bitfighter/blob/master/tnl/udp.cpp

but creating a test case with pulling out just the `htonl` links just fine.

**Comment by kripken** [comment]
If you want, send me the entire bitcode file and build command and I'll debug that.

**Comment by raptor** [comment]
Here is the bitcode file (30MB, 52MB uncompressed):
http://bitfighter.org/~raptor/bitfighter.bc.2.zip

My final linking command was this:
```
~/apps/emsdk_portable/emscripten/incoming/em++    -g -s USE_SDL=2 -s LEGACY_GL_EMULATION=1 -s GL_UNSAFE_OPTS=0 -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1 -s DEMANGLE_SUPPORT=1 -DNDEBUG -O2    --preload-file ~/code/git/bitfighter/resource@/ -O2 @CMakeFiles/bitfighter.dir/objects1.rsp  -o ../../exe/bitfighter.bc  ../../lib/liblua.a ../tnl/libtnl.a ../tomcrypt/libtomcrypt.so ../clipper/libclipper.a ../poly2tri/libpoly2tri.a -lm ../../lib/libphysfs.a
```
Thank you very much!

**Comment by kripken** [comment]
Is that the command you want me to run to reproduce the problem? The preload needs files I don't have, also there are a bunch of `.a`s? I tried to run

````
em++ -g -s USE_SDL=2 -s LEGACY_GL_EMULATION=1 -s GL_UNSAFE_OPTS=0 -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1 -s DEMANGLE_SUPPORT=1 -DNDEBUG -O2 -profiling bitfighter.bc
````

and it looks ok, I see a `htonl` method emitted and hooked up properly. Do you not see that when you run that command?

**Comment by raptor** [comment]
I must have misunderstood you - do you want to replicate how I build from the source code of my project?  I have a lot of code changes not checked in (including a couple of custom `.a` files.)

I am not completely familiar with with the build process, I'll pay attention with `EMCC_DEBUG=1` next time.

All I know is that that linking command at the end of compiling my whole project emits the `unresolved symbol: htonl`.

Also, after a few more tweaks, I got the game to run!  Network is broke, but it's rendering! (mostly):  http://bitfighter.org/~raptor/emscripten/bitfighter.html

**Comment by kripken** [comment]
Oh ok, yes, I do see that warning as well. It's spurious, since the method is actually there, but I should look into removing it.

The game seems to run ok, aside from complaining about networking, I could fly around and shoot. Very smooth frame rate, nice.

**Comment by kripken** [comment]
Spurious htonl warning should now be gone on incoming.

**Comment by raptor** [comment]
Yep, it goes away.  OK, I guess that my assumption that the missing `htonl` was part of the network problems, is false.

This issue can probably closed again as I have to do a deeper investigation on the network issues.  Is there anything specific I should do when attempting UDP networking?  I don't find much in the documentation that mentions UDP.

Thanks!

**Comment by kripken** [comment]
UDP should "just work", but (1) only async networking operatios work because of how the web works, and (2) really it's mostly just been tested on ENet, I wouldn't be surprised if there are bugs.
